; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro16]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0
upload_speed = 57600

; Wire ist Teil des Arduino-Core (kein extra Download nötig)
; PCA9685-Lib + Abhängigkeit
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library@^3.0.2
  adafruit/Adafruit BusIO@^1.17.0
