[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200

; Wire ist Teil des Arduino-Frameworks
; SX30 liegt lokal im Projekt unter lib/SX30

lib_deps =
  adafruit/Adafruit PWM Servo Driver Library@^3.0.2
  adafruit/Adafruit BusIO@^1.17.0
